"use strict"

module.exports = {};

module.exports.eeeCountries = [
  "germany",
  "austria",
  "belgium",
  "bulgaria",
  "cyprus",
  "croatia",
  "denmark",
  "spain",
  "estonia",
  "finland",
  "france",
  "greece",
  "hungary",
  "ireland",
  "italy",
  "latvia",
  "lithuania",
  "luxembourg",
  "malta",
  "netherlands",
  "poland",
  "portugal",
  "czech_republic",
  "romania",
  "uk",
  "slovakia",
  "slovenia",
  "sweden",
  "iceland",
  "liechtenstein",
  "norway",
];

// APS stuff -- see visaTypes.js for spreadsheet
var apsAgreements = {
  masters: "Diplôme au moins équivalent au master obtenu dans un établissement français",
  mastersOrLicensePro: "Licence professionnelle ou diplôme au moins équivalent au master obtenus dans un établissement français",
  mastersLicenseProNotFrance: "Licence professionnelle ou diplôme au moins équivalent au master obtenus dans un établissement " +
      "français ou dans un établissement du pays d'origine dans le cadre d'une convention de délivrance de diplômes en partenariat international",
};

// TODO: change these to lower case and fix balkans
module.exports.apsSpecialCountries = {
  "Balkans": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersLicenseProNotFrance,
    condition_de_duree: 12,
    renouvellement: false
  },
  "Benin": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 6,
    renouvellement: true,
    renouvellement_count: 1,
  },
  "Burkina Faso": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersLicenseProNotFrance,
    condition_de_duree: 6,
    renouvellement: true,
    renouvellement_count: 1,
  },
  "Cameroun": {
    applicable: true,
    accord_special: false,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Cap vert": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.masters,
    condition_de_duree: 9,
    renouvellement: false,
  },
  "congo": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.masters,
    condition_de_duree: 9,
    renouvellement: false,
  },
  "ivory_coast": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.masters,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "gabon": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 9,
    renouvellement: true,
    renouvellement_count: 1,
  },
  "Inde": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.masters,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Liban": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.masters,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Macédoine": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Mali": {
    applicable: true,
    accord_special: false,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Maroc": {
    applicable: true,
    accord_special: false,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Maurice": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersLicenseProNotFrance,
    condition_de_duree: 6,
    renouvellement: true,
    renouvellement_count: 1,
  },
  "Mauritanie": {
    applicable: true,
    accord_special: false,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Monténégro": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersLicenseProNotFrance,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Niger": {
    applicable: true,
    accord_special: false,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "République centrafricaine": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Russie": {
    applicable: true,
    accord_special: false,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Sénégal": {
    applicable: true,
    accord_special: false,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Serbie": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersLicenseProNotFrance,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Togo": {
    applicable: true,
    accord_special: false,
    condition_de_diplome: apsAgreements.mastersOrLicensePro,
    condition_de_duree: 12,
    renouvellement: false,
  },
  "Tunisie": {
    applicable: true,
    accord_special: true,
    condition_de_diplome: apsAgreements.mastersLicenseProNotFrance,
    condition_de_duree: 6,
    renouvellement: true,
    renouvellement_count: 1,
  },
};
